# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 548c337085aed8c38c0eb772db9f6ac8427428b340c23ff34d51868d1abefc7492880fe495889adce28e93600c2abc2b9e34fc018b70e05f02a95b7c61a2abd8
  STRIPE_PUBLISHABLE_KEY: pk_test_GZtYHFjr2VJ0qU5o0TO629Df
  STRIPE_SECRET_KEY: sk_test_iUhE5OPoLP6Y3cp3qMc3SAxu

test:
  secret_key_base: da9f783042108954ac473f557a4f42eef168d68961092451a0d0e3120fa4b68f283daf1e61c237f2c7fcb89549d2ec28b63e5a8f1ac1c041db581935c472d8a9
  STRIPE_PUBLISHABLE_KEY: pk_test_GZtYHFjr2VJ0qU5o0TO629Df
  STRIPE_SECRET_KEY: sk_test_iUhE5OPoLP6Y3cp3qMc3SAxu

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  STRIPE_PUBLISHABLE_KEY: pk_test_GZtYHFjr2VJ0qU5o0TO629Df
  STRIPE_SECRET_KEY: sk_test_iUhE5OPoLP6Y3cp3qMc3SAxu
